export const EVENT_CONSTANT = [
  "Workshop",
  "Hands-on Workshop",
  "Seminar",
  "Conference",
  "Webinar",
  "Meetup",
  "Hackathon",
  "Code Lab",
  "Bootcamp",
  "Panel Discussion",
  "Tech Talk",
  "AMA Session",
  "Networking Event",
  "Startup Pitch",
  "Product Launch",
  "Demo Day",
  "Training Session",
  "Certification Program",
  "Competition",
  "Challenge",
  "Community Meetup",
  "Open Source Sprint",
  "Volunteer Event",
  "Charity Event",
  "Festival",
  "Concert",
  "Sports Event",
  "Trade Show",
];

export const EVENT_CATEGORY = [
  "Technology",
  "Artificial Intelligence",
  "Machine Learning",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Cybersecurity",
  "Data Science",
  "Open Source",
  "DevOps",
  "Startup",
  "Entrepreneurship",
  "Business",
  "Product Management",
  "Education",
  "Career Development",
  "Leadership",
  "Design / UI-UX",
  "Marketing",
  "Finance",
  "Health",
  "Social Impact",
  "Community",
  "Entertainment",
  "Music",
  "Art",
  "Sports",
];

export const EventMode_Constant = ["ONLINE", "OFFLINE", "HYBRID"];

export const EventVisibility_Constant = ["PUBLIC", "PRIVATE", "UNLISTED", "DRAFT"];

export const EventStatus_Constant = [
  "REGISTRATION_OPEN",
  "REGISTRATION_CLOSED",
  "LIVE",
  "COMPLETED",
  "CANCELLED",
];
